version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./data:/app/server/data
      - ./uploads:/app/server/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000 